spring.application.name=File-service

server.port=8081

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection (In-Memory)
spring.datasource.url=jdbc:h2:mem:drivedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Rushi@845977

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB